python/django/meng/meng/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import hello
import books.views
import contact.views

urlpatterns = [
    # Examples:
    # url(r'^$', 'meng.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello/(?P<name>\w+)$', hello.greeting, { 'message' : 'hello'}),
    url(r'^bye/(?P<name>\w+)$', hello.greeting, { 'message' : 'bye'}),
    url(r'^header/$', hello.display_head),
    url(r'^search/$', books.views.search),
    url(r'^time/$', hello.time),
    url(r'^header/$', hello.display_head),
    url(r'^contact/$', contact.views.contact),
    url(r'^contact/thanks/$', contact.views.contact_thanks),
]

python/django/meng/books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length = 30)
    address = models.CharField(max_length = 50)
    city = models.CharField(max_length = 60)
    state_province = models.CharField(max_length = 30)
    country = models.CharField(max_length = 50)
    website = models.URLField()

    def __str__(self):
        return '{}'.format(self.name)


class Author(models.Model):
    first_name = models.CharField(max_length = 30)
    last_name = models.CharField(max_length = 40)
    email = models.EmailField(blank = True)

    def __unicode__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Book(models.Model):
    title = models.CharField(max_length = 100)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    author = models.ManyToManyField(Author)

    def __str__(self):
        return '{}'.format(self.title)

python/django/meng/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(required = False)
    subject = forms.CharField()
    message = forms.CharField(widget = forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num = len(message.split())
        if num < 4:
            raise forms.ValidationError("Not enough words!")
        return message

python/django/meng/books/views.py
from django.shortcuts import render
from django.http import HttpResponse
import models


def search(request):
    name = request.GET.get('q', None)
    errors = []
    if name is not None:
        if not name:
            errors.append("please enter a term.")
        elif len(name) > 20:
            errors.append("Please enter at most 20 characters.")
        else:
            booklist = models.Book.objects.filter(title__icontains = name)
            return render(request, 'search_results.html', { 'books' : booklist })
    return render(request, 'search_form.html', { 'errors' : errors })

python/django/meng/contact/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.template.context_processors import csrf
from forms import ContactForm


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            default_from = '287819708@qq.com'
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', default_from) or default_from,
                ['fancmong@mail.ustc.edu.cn'],
                fail_silently = False
            )
            return HttpResponseRedirect('/contact/thanks')
    else:
        form = ContactForm(initial = {'subject' : 'I love your site!'})
    return render(request, 'contact_form_custom.html', { 'form' : form })

def contact_thanks(request):
    return HttpResponse('<html><p>Thanks for contacting us!</p></html>')

python/django/meng/books/templates/search_form.html
<!DOCTYPE html>
<html>
    <head>
        <title>Search</title>
    </head>
    <body>
        {% if errors %}
            <ul>
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        <form action = "" method = "get">
            <input type = "text" name = "q">
            <input type = "submit" value = "search">
        </form>
    </body>
</html>

python/django/meng/books/templates/search_results.html
<html>
    <body>
    {% if books %}
        <h3>Found {{ books | length }} book{{ books | pluralize }}.</h3>
        <table border = "1" cellpadding = "10" style = "text-align:'center'">
            <tr>
                <th></th>
                <th>publisher</th>
                <th>publication date</th>
            </tr>
        {% for book in books %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ book.publisher }}</td>
                <td>{{ book.publication_date }}</td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No results found.</p>
    {% endif %}
    </body>
</html>

python/django/meng/templates/contact_form.html
<!DOCTYPE html>
<html>
    <head>
        <title>Contact us</title>
    </head>
    <body>
        <h1>Contact us</h1>
        {% if form.errors %}
        <p style="color:red">Please correct the error{{ form.errors | pluralize }} below</p>
        {% endif %}
        <form action="" method="post">{% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit">
        </form>
    </body>
</html>

python/django/meng/templates/contact_form_custom.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Email:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
        {% csrf_token %}
    </form>
</body>
</html>

python/django/meng/templates/current_time.html
<!DOCTYPE HTML>
<head>
    <h1>Welcome to my website!</h1>
    <p>It is now {{ current_time }}</p>
    <p>Your browser is {{ user_browser }}.</p>
</head>

python/django/meng/templates/display_head.html
<!DOCTYPE HTML>
<html>
    <h2>The information of the http header</h2>
    <title>display http header</title>
    <body>
        <table border = "1" cellpadding = "10">
            <tr>
                <th colspan = "2">path</th>
                <td>{{ request.path }}</td>
            </tr>
            <tr>
                <th colspan = "2">host</th>
                <td>{{ request.get_host }}</td>
            </tr>
            <tr>
                <th rowspan = {{ request | length }}>Meta</th>
            </tr>
            {% for pair in request.META.items %}
                <tr>
                    <td>{{ pair.0 }}</td>
                    <td>{{ pair.1 }}</td>
                </tr>
            {% endfor %}
        </table>
    </body>
</html>